/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import BO.Jugador;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class frameConfiguracionPartida extends javax.swing.JFrame {

    public static Color COLOR;
    public static Boolean ANFITRION;
    public static Integer CASILLAS;
    public static Integer APUESTA;
    public static ArrayList<Jugador> LISTA_JUGADORES;

    /**
     * Creates new form ConfiguracionPartida_A
     */
    public frameConfiguracionPartida() {
        LISTA_JUGADORES = new ArrayList<>();
        initComponents();
        lblNickname.setText(RegistroDeJuego.JUGADOR.getNombre());
        this.setTitle(frameCrearSala.NOMBRE_SALA);
        centrarVentana();
        this.getContentPane().setBackground(Color.decode("#FFFFFF"));
        if (COLOR != null) {
            RegistroDeJuego.JUGADOR.setColor(COLOR);
            btnColorChooser.setText("#" + (Integer.toHexString(COLOR.getRGB()).substring(2)).toUpperCase());
        }
        buttonRegistrarse.setEnabled(COLOR != null);
        ANFITRION = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblColorFichas = new javax.swing.JLabel();
        lblApuestas = new javax.swing.JLabel();
        lblNoCasillas = new javax.swing.JLabel();
        cbCasillas = new javax.swing.JComboBox<>();
        txtCantidadApuesta = new javax.swing.JTextField();
        lblDinero = new javax.swing.JLabel();
        lblNickname = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnColorChooser = new javax.swing.JButton();
        buttonRegistrarse = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuraciones");
        setMaximumSize(new java.awt.Dimension(471, 235));
        setMinimumSize(new java.awt.Dimension(471, 235));
        setResizable(false);
        getContentPane().setLayout(null);

        lblColorFichas.setText("Color de fichas");
        getContentPane().add(lblColorFichas);
        lblColorFichas.setBounds(40, 70, 100, 30);

        lblApuestas.setText("Cantidad de apuesta");
        getContentPane().add(lblApuestas);
        lblApuestas.setBounds(20, 100, 160, 40);

        lblNoCasillas.setText("Total de casillas");
        getContentPane().add(lblNoCasillas);
        lblNoCasillas.setBounds(40, 120, 140, 60);

        cbCasillas.setModel(cargarComboBox());
        getContentPane().add(cbCasillas);
        cbCasillas.setBounds(152, 140, 90, 20);
        getContentPane().add(txtCantidadApuesta);
        txtCantidadApuesta.setBounds(150, 100, 90, 30);

        lblDinero.setText("$");
        getContentPane().add(lblDinero);
        lblDinero.setBounds(130, 110, 6, 14);

        lblNickname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNickname.setText("『      』");
        getContentPane().add(lblNickname);
        lblNickname.setBounds(330, 130, 96, 29);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(20, 170, 53, 23);

        btnColorChooser.setText("...");
        btnColorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorChooserActionPerformed(evt);
            }
        });
        getContentPane().add(btnColorChooser);
        btnColorChooser.setBounds(152, 70, 90, 23);

        buttonRegistrarse.setText("Aceptar");
        buttonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRegistrarse);
        buttonRegistrarse.setBounds(270, 70, 177, 48);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TItulo_Configurar_Partida.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 0, 360, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_Configuracion.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 471, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        RegistroDeJuego pane = new RegistroDeJuego();
        pane.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnColorChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorChooserActionPerformed
        ANFITRION = true;
        frmColor choser = new frmColor();
        choser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnColorChooserActionPerformed

    private void buttonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarseActionPerformed
        if(COLOR != null){
            CASILLAS = (Integer) cbCasillas.getSelectedItem();
//            frameEsperaPartida pane = new frameEsperaPartida();
            framePartida pane = new framePartida();
            pane.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(this, "Favor de seleccionar un color.", "Información.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonRegistrarseActionPerformed

    /**
     * Método para centrar la ventana en la pantalla.
     */
    private void centrarVentana() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();

        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }

        setLocation((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
    }

    private DefaultComboBoxModel<Integer> cargarComboBox() {
        DefaultComboBoxModel<Integer> defaultComboBoxModel = new DefaultComboBoxModel<>();
        defaultComboBoxModel.addElement(36);
        defaultComboBoxModel.addElement(44);
        defaultComboBoxModel.addElement(52);
        defaultComboBoxModel.addElement(60);
        return defaultComboBoxModel;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColorChooser;
    private javax.swing.JButton btnSalir;
    private javax.swing.JToggleButton buttonRegistrarse;
    private javax.swing.JComboBox<Integer> cbCasillas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblApuestas;
    private javax.swing.JLabel lblColorFichas;
    private javax.swing.JLabel lblDinero;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblNoCasillas;
    private javax.swing.JTextField txtCantidadApuesta;
    // End of variables declaration//GEN-END:variables
}
