/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import BO.Jugador;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class RegistroDeJuego extends javax.swing.JFrame {

    public static String SALA;
    public static Integer DINERO;
    public static Jugador JUGADOR = new Jugador();
    private Random r;

    /**
     * Creates new form RegistroDeJuego
     */
    public RegistroDeJuego() {
        initComponents();
        if(JUGADOR != null){
            txtNickname.setText(JUGADOR.getNombre());
        }
        r = new Random();
        centrarVentana();
        this.getContentPane().setBackground(Color.decode("#FFFFFF"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNickname = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        btnCrearPartida = new javax.swing.JButton();
        btnUnirsePartida = new javax.swing.JButton();
        txtDinero = new javax.swing.JTextField();
        lblDinero = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(500, 417));
        setMinimumSize(new java.awt.Dimension(500, 417));
        setPreferredSize(new java.awt.Dimension(500, 417));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 417));
        getContentPane().setLayout(null);

        lblNickname.setText("Nombre");
        getContentPane().add(lblNickname);
        lblNickname.setBounds(70, 80, 80, 40);
        getContentPane().add(txtNickname);
        txtNickname.setBounds(140, 90, 223, 30);

        btnCrearPartida.setText("Crear partida");
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearPartida);
        btnCrearPartida.setBounds(140, 170, 223, 54);

        btnUnirsePartida.setText("Unirse a partida");
        btnUnirsePartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirsePartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnirsePartida);
        btnUnirsePartida.setBounds(140, 260, 223, 52);

        txtDinero.setEditable(false);
        getContentPane().add(txtDinero);
        txtDinero.setBounds(140, 130, 223, 30);

        lblDinero.setText("Dinero");
        getContentPane().add(lblDinero);
        lblDinero.setBounds(70, 130, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TItulo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 280, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_Menu.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-90, 0, 600, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnirsePartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirsePartidaActionPerformed
        if (!txtNickname.getText().isEmpty()) {
            declararNickname();
            String auxNombreSala = JOptionPane.showInputDialog(this, "Nombre Sala", "Ingresar a sala", JOptionPane.PLAIN_MESSAGE);
            if(auxNombreSala.equals(frameCrearSala.NOMBRE_SALA)){
                
            }
        } else {
            JOptionPane.showMessageDialog(this, "Favor de ingresar un nombre de usuario.", "Información", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUnirsePartidaActionPerformed

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed
        if (!txtNickname.getText().isEmpty()) {
            declararNickname();
            SALA = generarNombreSala();
            JOptionPane.showMessageDialog(this, SALA, "Nombre de la sala", JOptionPane.INFORMATION_MESSAGE);
            frameConfiguracionPartida pane = new frameConfiguracionPartida();
            pane.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Favor de ingresar un nombre de usuario.", "Información", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearPartidaActionPerformed

    /**
     * Método para centrar la ventana en la pantalla.
     */
    private void centrarVentana() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();

        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }

        setLocation((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
    }
    
    private void declararNickname() {
        JUGADOR.setNombre(txtNickname.getText());
    }

    public String getNickname() {
        return JUGADOR.getNombre();
    }

    private String generarNombreSala() {
//        
//        StringBuilder sb = new StringBuilder(); 
//        for(int i = 0; i < 6; i++) { 
//            char c = (char)(r.nextInt((int)(Character.MAX_VALUE))); 
//            sb.append(c); 
//        } 
//        return sb.toString(); 

        char[] elementos = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'ñ', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M','N','Ñ','O','P','Q','R','S','T' ,'U','V','W','X','Y','Z'};
        char[] conjunto = new char[8];
        for (int i = 0; i < 6; i++) {
            int el = (int) (Math.random() * 37);
            conjunto[i] = (char) elementos[el];
        }
        return new String(conjunto);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDeJuego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDeJuego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDeJuego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDeJuego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDeJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JButton btnUnirsePartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDinero;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JTextField txtDinero;
    private javax.swing.JTextField txtNickname;
    // End of variables declaration//GEN-END:variables
}
